name: CodeGena Workflow
on: [push, pull_request]

jobs:
  format-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: YAPF Python Code Formatting Check
        # You may pin to the exact commit or the version.
        # uses: AlexanderMelde/yapf-action@a2053dba9adceb173b38e58acaad7436a1934bdd
        uses: AlexanderMelde/yapf-action@v1.0
        
      - name: Ruff Check
        # You may pin to the exact commit or the version.
        # uses: jpetrucciani/ruff-check@95ff5ea372c5099efb7a38151f8aef8fee435c47
        uses: jpetrucciani/ruff-check@0.1.0
        with:
          # File or directory to run ruff on
          path: '.' # optional, default is.
          # Optional ruff flags (refer to `ruff --help`)
          flags: '' # optional, default is empty string
          # Format to output ruff messages in
          format: 'github' # optional, default is github
