name: CodeGena Workflow
on: [push, pull_request]

jobs:
  format-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: YAPF Python Code Formatting Check
        uses: AlexanderMelde/yapf-action@v1.0
        
      - name: Ruff Check
        uses: jpetrucciani/ruff-check@0.1.0
        with:
          path: '.'
          flags: ''
          format: 'github'
  test:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        
        # Set up Python environment
        - name: Set up Python 3.10
          uses: actions/setup-python@v2
          with:
            python-version: '3.10'
          
        - name: Install the reprocess package
          run: |
            pip install .

        # Install dependencies
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
            pip install pytest

        # Run tests
        - name: Run tests with pytest
          run: pytest tests/ -s