name: CodeGena Workflow
on: [push, pull_request]

jobs:
  format-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: YAPF Formatter
        uses: diegovalenzuelaiturra/yapf-action@v0.0.5
        with:
          args: --verbose --parallel --recursive --in-place
        
      - name: Ruff Check
        uses: jpetrucciani/ruff-check@0.1.0
        with:
          path: '.'
          flags: ''
          format: 'github'
